refactor: multiple changes to Dockerfile and executables
zanata/zanata-docker-files pull request #12
Opened 2016-12-13 23:41 UTC by carlosmunoz

Add ZANATA_HOME environment variable instead of user.home in
standalone.xml
Use curl to download dependencies in the Dockerfile instead of
needing to isntall yum
Remove some dependencies between the two running containers
Change some volume mappings

2016-12-13 23:42 UTC, carlosmunoz commented
_This has been pair-programmed with @seanf. Assigning him as reviewer for final confirmation._

2016-12-14 02:12 UTC, seanf commented on zanata-server/runapp.sh
> +    ZanataVer=latest
I don't have a problem with this change, but @definite should take a look at it. The right implementation depends on how we expect people to use this script.

2016-12-14 03:57 UTC, definite requested changes

2016-12-14 03:57 UTC, definite commented on zanata-server/runapp.sh
> +    ZanataVer=latest
The only problem it that if we forget to push the version, it won't have error message. Perhaps we can change comment into 
"Use the latest version (not necessary the version defined in Dockerfile"

2016-12-14 23:49 UTC, definite approved these changes

2016-12-14 23:51 UTC, definite commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

---

Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-docker-files/12#-:-KYzjccXANMmPA12vMas:bnfp4nl)*
<!-- Sent from Reviewable.io -->

2016-12-14 23:52 UTC, carlosmunoz commented
@djansen-redhat Would you mind verifying this one?

2016-12-15 06:11 UTC, djansen-redhat commented
@carlosmunoz looks good to me

2016-12-15 06:13 UTC, merged